<section class="find_form clifx">
	<form action="" method="post">
		<p class="user">
			<label for="nickname" class="optional">用户名</label> <input
				name="nickname" id="nickname" value="" type="text">
		</p>
		<p class="email_area">
			<label for="emailname">邮箱账号</label> <input name="email" id="email"
				value="" type="text">
		</p>
		<p class="btn">
			<input type="submit" id="find_submit" class="find" value="找回密码" /> <a
				href="/index/login">登陆</a>
		</p>
	</form>
</section>
<aside class="notice" style="text-align: left; text-indent: 420px;">
	温馨提示: 输入用户名和注册邮箱账号，确认提交后，你的邮箱会收到一封邮件，可进行密码修改。</aside>
<script type="text/javascript">
 	$("#find_submit").click(function(){
	 		var url = '/<?php echo BLOGGER_NAME?>/user/find';
			$.post(url,
				   {ajax:'1',nickname:$("#nickname").val(),email:$("#email").val()},
				   function(data){
					   if(data=="ok"){
						   alert("密码已发到您的邮箱，请注意查收！");
						   window.location = "/index/login";
					   }else{
							alert("你输入的用户名和邮箱不匹配，请重试！");
					   }
				   });	
			return false;
 	 	});
</script>