<tr> 
    <td class='td_links'> 
        <a href='/menuitem/update/id/<?php echo $this->id;?>'>修改</a> | 
        <a href='/menuitem/move/direction/up/id/<?php echo $this->id;?>'>上移</a> | 
        <a href='/menuitem/move/direction/down/id/<?php echo $this->id;?>'>下移</a> | 
        <a href='/menuitem/delete/id/<?php echo $this->id;?>'>删除</a> 
    </td> 
    <td><?php echo $this->label ?></td> 
    <td><?php echo $this->link ?></td>
    <td><?php if($this->access_rule=='member'){echo "所有用户";}else{echo "仅博主";} ?></td>
</tr> 