<section class="login_form clifx">
	<form action="" method="post">
		<p class="user">
			<label for="name" class="optional">用户名</label>
			<input name="name" id="name" value="" type="text">
		</p>
		<p class="pwd">
			<label for="password" class="optional">密码</label>
			<input name="password" id="password" value="" type="password">
		</p>
		<p class="btn">
			<input type="submit" name="login" class="login" value="登陆"/>
			<a href="/index/find">忘记密码？</a>
		</p>
		<span class="regist"><a href="/register">免费注册一个账号</a></span>
	</form>
</section>
