<tr> 
    <td class='links handle'> 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/memfriendlink/update/id/<?php echo $this->id;?>'>修改</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/memfriendlink/move/direction/up/id/<?php echo $this->id;?>'> 
           上移</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/memfriendlink/move/direction/down/id/<?php echo $this->id;?>'> 
           下移</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/memfriendlink/delete/id/<?php echo $this->id;?>'>删除</a> 
    </td> 
    <td><?php echo $this->label ?></td> 
    <td><?php echo $this->link ?></td>
</tr> 