<tr> 
    <td class='links'> 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/menuitem/update/id/<?php echo $this->id;?>'>Update</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/menuitem/move/direction/up/id/<?php echo $this->id;?>'> 
           Move up</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/menuitem/move/direction/down/id/<?php echo $this->id;?>'> 
           Move down</a> | 
        <a href='<?php echo '/'.BLOGGER_NAME;?>/menuitem/delete/id/<?php echo $this->id;?>'>Delete</a> 
    </td> 
    <td><?php echo $this->label ?></td> 
    <td><?php echo $this->link ?></td>
    <td><?php if($this->access_rule=='member'){echo "所有用户";}else{echo "仅博主";} ?></td>
</tr> 