<h2>Manage Menu Items</h2> 
<p>Current Menu: <?php echo $this->menu->name;?></p> 
<?php 
if($this->items != null) { 
?> 
<table> 
    <tr> 
        <th>Links </th> 
        <th>Label</th>  
        <th>Link</th> 
        <th>浏览权限</th>
    </tr> 
    <?php echo $this->partialLoop('partials/menuItemRow.phtml', 
        $this->items); ?> 
</table> 
<?php }else{?> 
<p>This menu does not have any items yet.</p> 
<?php }?> 
<p><a href='<?php echo '/'.BLOGGER_NAME;?>/menuitem/add/menu/<?php echo $this->menu->id ?>'>Add a new item</a></p> 